name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests and capture output
        run: ./gradlew test --info > test_results.txt || true
      - name: Send success message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Все ок, тесты прошли успешно!"
      - name: Set failed tests output as env var
        if: failure()
        run: echo "TEST_RESULTS=$(cat test_results.txt)" >> $GITHUB_ENV
      - name: Send failure message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "Тесты не прошли. Проверьте результаты:\n\n${{ env.TEST_RESULTS }}"
